{% set name = "scriptengine-tasks-hpc" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 677debc91681095142ea9b35304aa5faea8b9205c80ddb58293627e2d668e4bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=60
  run:
    - python >={{ python_min }}
    - scriptengine >=1.0.0

test:
  imports:
    - hpctasks.module
    - hpctasks.slurm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uwefladrich/scriptengine-tasks-hpc
  summary: ScriptEngine tasks you may need on HPC systems
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - uwefladrich
